# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Pieter van der Heijden
description:      'I am a CS student at the TU/e and freelance software developer at VCF Software Solutions. This is my personal blog.'
#url: https://pietervdheijden.me
#enforce_ssl: pietervdheijden.me
baseurl:          /
logo:             /content/images/me.jpg

author:
  name:           'Pieter van der Heijden'

paginate:         5

disqus_shortname: pietervdheijden

github:
  repo:           https://github.com/pietervdheijden/pietervdheijden.github.io

gems:
  - jekyll-sitemap

twitter: '@pieterheijden'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
